CREATE TABLE `bot_appointment_reminder_dispatches` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `legacy_agenda_id` INTEGER NOT NULL,
  `patient_legacy_user_id` INTEGER NOT NULL,
  `conversation_key` VARCHAR(191) NULL,
  `recipient_phone_raw` VARCHAR(32) NOT NULL,
  `recipient_phone_e164` VARCHAR(32) NULL,
  `appointment_starts_at` DATETIME(3) NOT NULL,
  `scheduled_for` DATETIME(3) NOT NULL,
  `reminder_type` VARCHAR(32) NOT NULL,
  `status` ENUM(
    'PENDING',
    'LOCKED',
    'PHONE_VERIFICATION_PENDING',
    'PHONE_VERIFICATION_EXPIRED',
    'SENT',
    'SKIPPED_NO_OPT_IN',
    'SKIPPED_INVALID_PHONE',
    'SKIPPED_APPOINTMENT_CANCELLED',
    'SKIPPED_APPOINTMENT_RESCHEDULED',
    'SKIPPED_LATE_CONFIRMATION',
    'SKIPPED_SUPPRESSED_CONTACT',
    'SKIPPED_HANDOFF_ACTIVE',
    'FAILED'
  ) NOT NULL DEFAULT 'PENDING',
  `template_name` VARCHAR(128) NOT NULL,
  `verification_template_name` VARCHAR(128) NOT NULL,
  `meta_message_id` VARCHAR(191) NULL,
  `verification_message_id` VARCHAR(191) NULL,
  `attempts` INTEGER NOT NULL DEFAULT 0,
  `next_attempt_at` DATETIME(3) NULL,
  `last_error` TEXT NULL,
  `lock_acquired_at` DATETIME(3) NULL,
  `lock_expires_at` DATETIME(3) NULL,
  `locked_by` VARCHAR(64) NULL,
  `lock_version` INTEGER NOT NULL DEFAULT 0,
  `verification_token_hash` VARCHAR(191) NULL,
  `verification_requested_at` DATETIME(3) NULL,
  `verification_expires_at` DATETIME(3) NULL,
  `sent_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `uq_bot_appt_reminder_dispatch_business`(`legacy_agenda_id`, `reminder_type`, `appointment_starts_at`),
  INDEX `idx_bot_appt_reminder_status_scheduled_for`(`status`, `scheduled_for`),
  INDEX `idx_bot_appt_reminder_status_next_attempt_at`(`status`, `next_attempt_at`),
  INDEX `idx_bot_appt_reminder_verification_expires_status`(`verification_expires_at`, `status`),
  INDEX `idx_bot_appt_reminder_lock_expires_status`(`lock_expires_at`, `status`),
  INDEX `idx_bot_appt_reminder_verification_token_hash`(`verification_token_hash`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `bot_webhook_inbound_dedup` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `provider` VARCHAR(32) NOT NULL,
  `inbound_message_id` VARCHAR(191) NOT NULL,
  `button_payload_id` VARCHAR(191) NOT NULL,
  `received_at` DATETIME(3) NOT NULL,
  `processed_at` DATETIME(3) NULL,
  `result_status` VARCHAR(64) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `uq_bot_webhook_inbound_dedup_key`(`provider`, `inbound_message_id`, `button_payload_id`),
  INDEX `idx_bot_webhook_inbound_dedup_provider_received_at`(`provider`, `received_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
