export const SURVEY_DISPATCH_REPOSITORY = Symbol('SURVEY_DISPATCH_REPOSITORY');
export const SATISFACTION_SURVEY_ELIGIBILITY_REPOSITORY = Symbol(
  'SATISFACTION_SURVEY_ELIGIBILITY_REPOSITORY',
);
export const SATISFACTION_SURVEY_LEGACY_STATUS_REPOSITORY = Symbol(
  'SATISFACTION_SURVEY_LEGACY_STATUS_REPOSITORY',
);
export const SURVEY_RECIPIENT_POLICY_REPOSITORY = Symbol('SURVEY_RECIPIENT_POLICY_REPOSITORY');
export const SATISFACTION_SURVEY_METRICS_REPOSITORY = Symbol(
  'SATISFACTION_SURVEY_METRICS_REPOSITORY',
);
