export const APPOINTMENT_REMINDER_DISPATCH_STATUSES = {
  PENDING: 'PENDING',
  LOCKED: 'LOCKED',
  PHONE_VERIFICATION_PENDING: 'PHONE_VERIFICATION_PENDING',
  PHONE_VERIFICATION_EXPIRED: 'PHONE_VERIFICATION_EXPIRED',
  SENT: 'SENT',
  SKIPPED_NO_OPT_IN: 'SKIPPED_NO_OPT_IN',
  SKIPPED_INVALID_PHONE: 'SKIPPED_INVALID_PHONE',
  SKIPPED_APPOINTMENT_CANCELLED: 'SKIPPED_APPOINTMENT_CANCELLED',
  SKIPPED_APPOINTMENT_RESCHEDULED: 'SKIPPED_APPOINTMENT_RESCHEDULED',
  SKIPPED_LATE_CONFIRMATION: 'SKIPPED_LATE_CONFIRMATION',
  SKIPPED_SUPPRESSED_CONTACT: 'SKIPPED_SUPPRESSED_CONTACT',
  SKIPPED_HANDOFF_ACTIVE: 'SKIPPED_HANDOFF_ACTIVE',
  FAILED: 'FAILED',
} as const;

export type AppointmentReminderDispatchStatus =
  (typeof APPOINTMENT_REMINDER_DISPATCH_STATUSES)[keyof typeof APPOINTMENT_REMINDER_DISPATCH_STATUSES];
