export const APPOINTMENT_REMINDER_METRICS_DEFAULT_LOOKBACK_HOURS = 24;
export const APPOINTMENT_REMINDER_METRICS_MIN_LOOKBACK_HOURS = 1;
export const APPOINTMENT_REMINDER_METRICS_MAX_LOOKBACK_HOURS = 168;
export const APPOINTMENT_REMINDER_METRICS_LOOKBACK_ERROR_MESSAGE =
  'lookbackHours must be an integer between 1 and 168.';
