export const APPOINTMENT_REMINDER_DISPATCH_REPOSITORY = Symbol(
  'APPOINTMENT_REMINDER_DISPATCH_REPOSITORY',
);

export const APPOINTMENT_REMINDER_ELIGIBILITY_REPOSITORY = Symbol(
  'APPOINTMENT_REMINDER_ELIGIBILITY_REPOSITORY',
);

export const APPOINTMENT_REMINDER_PATIENT_CONTACT_REPOSITORY = Symbol(
  'APPOINTMENT_REMINDER_PATIENT_CONTACT_REPOSITORY',
);

export const APPOINTMENT_REMINDER_RECIPIENT_POLICY_REPOSITORY = Symbol(
  'APPOINTMENT_REMINDER_RECIPIENT_POLICY_REPOSITORY',
);

export const APPOINTMENT_REMINDER_METRICS_REPOSITORY = Symbol(
  'APPOINTMENT_REMINDER_METRICS_REPOSITORY',
);
