export const WHATSAPP_SIGNATURE_VERIFIER = Symbol('WHATSAPP_SIGNATURE_VERIFIER');
export const WHATSAPP_PAYLOAD_PARSER = Symbol('WHATSAPP_PAYLOAD_PARSER');
export const WHATSAPP_WEBHOOK_IDEMPOTENCY_STORE = Symbol('WHATSAPP_WEBHOOK_IDEMPOTENCY_STORE');
export const WHATSAPP_WEBHOOK_INBOX_REPOSITORY = Symbol('WHATSAPP_WEBHOOK_INBOX_REPOSITORY');
export const WHATSAPP_MESSAGE_SENDER = Symbol('WHATSAPP_MESSAGE_SENDER');
