export const PATIENT_VALIDATION_REPOSITORY = Symbol('PATIENT_VALIDATION_REPOSITORY');
export const CONTRACTED_EPS_REPOSITORY = Symbol('CONTRACTED_EPS_REPOSITORY');
export const PATIENT_SPECIALTY_ELIGIBILITY_REPOSITORY = Symbol(
  'PATIENT_SPECIALTY_ELIGIBILITY_REPOSITORY',
);
export const WHATSAPP_CONTACT_CONSENT_REPOSITORY = Symbol(
  'WHATSAPP_CONTACT_CONSENT_REPOSITORY',
);
