export const CONVERSATION_STATES = {
  MAIN_MENU: 'MAIN_MENU',
  WAITING_DOCUMENT: 'WAITING_DOCUMENT',
  WAITING_BIRTH_DATE: 'WAITING_BIRTH_DATE',
  PATIENT_VALIDATED: 'PATIENT_VALIDATED',
  CONFIRMING_PATIENT_CONTACT: 'CONFIRMING_PATIENT_CONTACT',
  SELECTING_CONTACT_UPDATE_FIELD: 'SELECTING_CONTACT_UPDATE_FIELD',
  UPDATING_CONTACT_PHONE: 'UPDATING_CONTACT_PHONE',
  UPDATING_CONTACT_EMAIL: 'UPDATING_CONTACT_EMAIL',
  SELECTING_ASSIGNED_APPOINTMENT: 'SELECTING_ASSIGNED_APPOINTMENT',
  REVIEWING_ASSIGNED_APPOINTMENT_ACTIONS:
    'REVIEWING_ASSIGNED_APPOINTMENT_ACTIONS',
  REVIEWING_ASSIGNED_APPOINTMENT_DETAILS:
    'REVIEWING_ASSIGNED_APPOINTMENT_DETAILS',
  SELECTING_SPECIALTY: 'SELECTING_SPECIALTY',
  SELECTING_APPOINTMENT_DATE: 'SELECTING_APPOINTMENT_DATE',
  SELECTING_APPOINTMENT_DOCTOR: 'SELECTING_APPOINTMENT_DOCTOR',
  SELECTING_APPOINTMENT_TIME: 'SELECTING_APPOINTMENT_TIME',
  REQUESTING_WHATSAPP_APPOINTMENT_NOTIFICATIONS_OPT_IN:
    'REQUESTING_WHATSAPP_APPOINTMENT_NOTIFICATIONS_OPT_IN',
} as const;

export type ConversationState =
  (typeof CONVERSATION_STATES)[keyof typeof CONVERSATION_STATES];
