export const CONVERSATION_STATES = {
  MAIN_MENU: 'MAIN_MENU',
  WAITING_DOCUMENT: 'WAITING_DOCUMENT',
  WAITING_BIRTH_DATE: 'WAITING_BIRTH_DATE',
  PATIENT_VALIDATED: 'PATIENT_VALIDATED',
  SELECTING_SPECIALTY: 'SELECTING_SPECIALTY',
  SELECTING_APPOINTMENT_DATE: 'SELECTING_APPOINTMENT_DATE',
  SELECTING_APPOINTMENT_TIME: 'SELECTING_APPOINTMENT_TIME',
} as const;

export type ConversationState =
  (typeof CONVERSATION_STATES)[keyof typeof CONVERSATION_STATES];
