export const CONVERSATION_SESSION_REPOSITORY = Symbol('CONVERSATION_SESSION_REPOSITORY');
export const CONVERSATION_PERSISTENCE_REPOSITORY = Symbol('CONVERSATION_PERSISTENCE_REPOSITORY');
export const CONVERSATION_MESSAGE_REPOSITORY = Symbol('CONVERSATION_MESSAGE_REPOSITORY');
