export const APPOINTMENT_AVAILABILITY_REPOSITORY = Symbol('APPOINTMENT_AVAILABILITY_REPOSITORY');
export const APPOINTMENT_ASSIGNMENT_REPOSITORY = Symbol('APPOINTMENT_ASSIGNMENT_REPOSITORY');
export const APPOINTMENT_PENDING_CHECK_REPOSITORY = Symbol('APPOINTMENT_PENDING_CHECK_REPOSITORY');
export const APPOINTMENT_CONFIRMATION_DETAILS_REPOSITORY = Symbol(
  'APPOINTMENT_CONFIRMATION_DETAILS_REPOSITORY',
);
