export const APPOINTMENT_AVAILABILITY_REPOSITORY = Symbol('APPOINTMENT_AVAILABILITY_REPOSITORY');
export const APPOINTMENT_ASSIGNMENT_REPOSITORY = Symbol('APPOINTMENT_ASSIGNMENT_REPOSITORY');
export const APPOINTMENT_PENDING_CHECK_REPOSITORY = Symbol('APPOINTMENT_PENDING_CHECK_REPOSITORY');
export const APPOINTMENT_CONFIRMATION_DETAILS_REPOSITORY = Symbol(
  'APPOINTMENT_CONFIRMATION_DETAILS_REPOSITORY',
);
export const APPOINTMENT_ASSIGNED_LIST_REPOSITORY = Symbol(
  'APPOINTMENT_ASSIGNED_LIST_REPOSITORY',
);
export const APPOINTMENT_CANCELLATION_REPOSITORY = Symbol('APPOINTMENT_CANCELLATION_REPOSITORY');
export const APPOINTMENT_RESCHEDULING_REPOSITORY = Symbol('APPOINTMENT_RESCHEDULING_REPOSITORY');
