#!/bin/sh

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${WHATSAPP_BOT_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${WHATSAPP_BOT_DB_APP_USER}'@'%'
  IDENTIFIED BY '${WHATSAPP_BOT_DB_APP_PASSWORD}';

CREATE USER IF NOT EXISTS '${WHATSAPP_BOT_DB_MIGRATION_USER}'@'%'
  IDENTIFIED BY '${WHATSAPP_BOT_DB_MIGRATION_PASSWORD}';

GRANT SELECT, INSERT, UPDATE, DELETE
  ON \`${WHATSAPP_BOT_DB_NAME}\`.*
  TO '${WHATSAPP_BOT_DB_APP_USER}'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE,
      CREATE, ALTER, DROP, INDEX, REFERENCES,
      CREATE TEMPORARY TABLES, LOCK TABLES
  ON \`${WHATSAPP_BOT_DB_NAME}\`.*
  TO '${WHATSAPP_BOT_DB_MIGRATION_USER}'@'%';

FLUSH PRIVILEGES;
SQL
