export const ADMIN_AUTH_USER_REPOSITORY = Symbol('ADMIN_AUTH_USER_REPOSITORY');
export const ADMIN_AUTH_SESSION_REPOSITORY = Symbol(
  'ADMIN_AUTH_SESSION_REPOSITORY',
);
export const ADMIN_AUTH_AUDIT_REPOSITORY = Symbol(
  'ADMIN_AUTH_AUDIT_REPOSITORY',
);
